/**
 * Web bridge contract — the JSON shapes that travel between the online
 * ordering website (apps/web, Next.js on Vercel + Neon Postgres) and the
 * POS bridge worker (apps/pos/electron/services/web-orders-bridge.ts).
 *
 * Flow:
 *   1. POS publishes its menu → PUT /api/bridge/menu  (PublishedMenu)
 *   2. Customer orders on the site → row in web_orders (WebOrder, status 'new')
 *   3. POS polls GET /api/bridge/orders?status=new → imports each order
 *      locally (mode 'delivery', source 'web') → POST .../ack with the local
 *      order number
 *   4. As the order advances on the Live Orders board, the POS pushes
 *      POST .../status so the customer's tracking page stays live.
 *
 * All money in cents, all rates in basis points — same discipline as the POS.
 */

export interface PublishedMenuItem {
  /** POS menu_items.id — the bridge uses this to add real order items. */
  posItemId: string;
  name: string;
  description: string | null;
  basePriceCents: number;
  /** Snapshot of the tax rate so the cart can estimate totals. */
  taxRateBps: number;
  imageUrl: string | null;
  sortOrder: number;
  modifierGroups: PublishedModifierGroup[];
}

export interface PublishedModifierGroup {
  posGroupId: string;
  name: string;
  selectionType: 'single' | 'multi';
  minSelect: number;
  maxSelect: number;
  isRequired: boolean;
  sortOrder: number;
  modifiers: PublishedModifier[];
}

export interface PublishedModifier {
  posModifierId: string;
  name: string;
  priceDeltaCents: number;
  isDefault: boolean;
  sortOrder: number;
}

export interface PublishedMenuCategory {
  posCategoryId: string;
  name: string;
  displayOrder: number;
  items: PublishedMenuItem[];
}

export interface PublishedMenu {
  categories: PublishedMenuCategory[];
  /** ISO timestamp of the publish — site shows menus only if non-stale. */
  publishedAt: string;
  store: {
    name: string;
    phone: string | null;
    whatsapp: string | null;
    addressLine: string | null;
    tagline: string | null;
  };
}

/** Customer-side order line as captured by the website cart. */
export interface WebOrderItem {
  posItemId: string;
  name: string;
  quantity: number;
  /** Price shown to the customer at order time (estimate; POS recomputes). */
  unitPriceCents: number;
  modifiers: Array<{
    posModifierId: string;
    name: string;
    priceDeltaCents: number;
  }>;
  notes: string | null;
}

/**
 * How the customer gets the food. 'pickup' = collected from the shop, with
 * PICKUP_DISCOUNT_PERCENT off. Orders from sites that predate pickup carry no
 * fulfilment field and are deliveries.
 */
export type WebFulfilment = 'delivery' | 'pickup';

/**
 * The printed menu's offer: "15% OFF · order online & pick up" (owner,
 * 2026-09-25; was 10% in v0.7.0). This is the percent the till applies at
 * import; it announces it in its heartbeat so the website always shows the
 * discount the till will actually bill.
 */
export const PICKUP_DISCOUNT_PERCENT = 15;

/** What a till that offers pickup but sends no percent (v0.7.0) applies. */
export const LEGACY_PICKUP_DISCOUNT_PERCENT = 10;

/**
 * Capabilities a till announces in its heartbeat (PUT /api/bridge/status).
 * The site only offers pickup while the listening till says it can import
 * pickup orders — an older POS would book them as deliveries at full price.
 */
export type TillFeature = 'pickup';

/** Body for PUT /api/bridge/status (the till's heartbeat). */
export interface BridgeHeartbeatBody {
  acceptingOrders: boolean;
  deviceId?: string | null;
  features?: TillFeature[];
  /** The pickup discount this till applies (absent from v0.7.0: 10). */
  pickupDiscountPercent?: number;
}

export type WebOrderStatus =
  | 'new' // placed on the site, not yet seen by the POS
  | 'accepted' // imported into the POS (ack'd)
  | 'preparing'
  | 'ready'
  | 'out_for_delivery'
  | 'delivered'
  | 'cancelled';

export interface WebOrder {
  /** UUID generated by the website. */
  id: string;
  status: WebOrderStatus;
  customerName: string;
  customerPhone: string;
  /** For a pickup order, a fixed "collect from the shop" line. */
  addressLine: string;
  area: string | null;
  notes: string | null;
  /** Absent on orders from sites that predate pickup: a delivery. */
  fulfilment?: WebFulfilment;
  items: WebOrderItem[];
  /** Estimates computed by the site; the POS receipt is authoritative. */
  subtotalCents: number;
  /** The pickup discount the site showed (0 for deliveries). */
  discountCents?: number;
  taxCents: number;
  totalCents: number;
  paymentMethod: 'cod';
  createdAt: string;
  /** Set when the POS imports the order. */
  posOrderId: string | null;
  posOrderNumber: string | null;
}

/** Body for POST /api/bridge/orders/:id/ack */
export interface BridgeAckBody {
  posOrderId: string;
  posOrderNumber: string;
}

/** Body for POST /api/bridge/orders/:id/status */
export interface BridgeStatusBody {
  status: Exclude<WebOrderStatus, 'new'>;
}
