/**
 * Web bridge contract — the JSON shapes that travel between the online
 * ordering website (apps/web, Next.js on Vercel + Neon Postgres) and the
 * POS bridge worker (apps/pos/electron/services/web-orders-bridge.ts).
 *
 * Flow:
 *   1. POS publishes its menu → PUT /api/bridge/menu  (PublishedMenu)
 *   2. Customer orders on the site → row in web_orders (WebOrder, status 'new')
 *   3. POS polls GET /api/bridge/orders?status=new → imports each order
 *      locally (mode 'delivery', source 'web') → POST .../ack with the local
 *      order number
 *   4. As the order advances on the Live Orders board, the POS pushes
 *      POST .../status so the customer's tracking page stays live.
 *
 * All money in cents, all rates in basis points — same discipline as the POS.
 */

export interface PublishedMenuItem {
  /** POS menu_items.id — the bridge uses this to add real order items. */
  posItemId: string;
  name: string;
  description: string | null;
  basePriceCents: number;
  /** Snapshot of the tax rate so the cart can estimate totals. */
  taxRateBps: number;
  imageUrl: string | null;
  sortOrder: number;
  modifierGroups: PublishedModifierGroup[];
}

export interface PublishedModifierGroup {
  posGroupId: string;
  name: string;
  selectionType: 'single' | 'multi';
  minSelect: number;
  maxSelect: number;
  isRequired: boolean;
  sortOrder: number;
  modifiers: PublishedModifier[];
}

export interface PublishedModifier {
  posModifierId: string;
  name: string;
  priceDeltaCents: number;
  isDefault: boolean;
  sortOrder: number;
}

export interface PublishedMenuCategory {
  posCategoryId: string;
  name: string;
  displayOrder: number;
  items: PublishedMenuItem[];
}

export interface PublishedMenu {
  categories: PublishedMenuCategory[];
  /** ISO timestamp of the publish — site shows menus only if non-stale. */
  publishedAt: string;
  store: {
    name: string;
    phone: string | null;
    whatsapp: string | null;
    addressLine: string | null;
    tagline: string | null;
  };
}

/** Customer-side order line as captured by the website cart. */
export interface WebOrderItem {
  posItemId: string;
  name: string;
  quantity: number;
  /** Price shown to the customer at order time (estimate; POS recomputes). */
  unitPriceCents: number;
  modifiers: Array<{
    posModifierId: string;
    name: string;
    priceDeltaCents: number;
  }>;
  notes: string | null;
}

export type WebOrderStatus =
  | 'new' // placed on the site, not yet seen by the POS
  | 'accepted' // imported into the POS (ack'd)
  | 'preparing'
  | 'ready'
  | 'out_for_delivery'
  | 'delivered'
  | 'cancelled';

export interface WebOrder {
  /** UUID generated by the website. */
  id: string;
  status: WebOrderStatus;
  customerName: string;
  customerPhone: string;
  addressLine: string;
  area: string | null;
  notes: string | null;
  items: WebOrderItem[];
  /** Estimates computed by the site; the POS receipt is authoritative. */
  subtotalCents: number;
  taxCents: number;
  totalCents: number;
  paymentMethod: 'cod';
  createdAt: string;
  /** Set when the POS imports the order. */
  posOrderId: string | null;
  posOrderNumber: string | null;
}

/** Body for POST /api/bridge/orders/:id/ack */
export interface BridgeAckBody {
  posOrderId: string;
  posOrderNumber: string;
}

/** Body for POST /api/bridge/orders/:id/status */
export interface BridgeStatusBody {
  status: Exclude<WebOrderStatus, 'new'>;
}
