import type { PrinterWidth } from '@cheeseoclock/shared-types';
import { EscPosBuilder } from '@cheeseoclock/printer-core';

/** A short test receipt to verify the printer cable, paper, and ESC/POS path. */
export function renderTestPage(width: PrinterWidth): Uint8Array {
  const b = new EscPosBuilder(width);
  b.align('center')
    .doubleSize(true)
    .bold(true)
    .text('TEST PAGE')
    .newline()
    .doubleSize(false)
    .bold(false)
    .text('CheeseOclock POS')
    .newline()
    .newline()
    .align('left')
    .rule()
    .line('Date', new Date().toISOString().slice(0, 19).replace('T', ' '))
    .line('Width', `${width} cols`)
    .line('Transport', 'OK')
    .rule()
    .newline()
    .text('Alignment check:')
    .newline()
    .align('left')
    .text('LEFT')
    .newline()
    .align('center')
    .text('CENTER')
    .newline()
    .align('right')
    .text('RIGHT')
    .newline()
    .align('left')
    .newline()
    .text('Styles:')
    .newline()
    .text('normal ')
    .bold(true)
    .text('bold ')
    .bold(false)
    .underline(true)
    .text('underline')
    .underline(false)
    .newline()
    .doubleSize(true)
    .text('BIG')
    .doubleSize(false)
    .newline()
    .newline()
    .align('center')
    .text('If you can read this, your printer is wired correctly.')
    .newline()
    .cut(true);
  return b.build();
}
