import { v7 as uuidv7 } from 'uuid';
import { z } from 'zod';
import { sql } from '@/lib/db';
import { deliveryChargeItemFor, findZone } from '@/lib/delivery-zones';
import { formatCents, normalizePhone } from '@/lib/format';
import { validateModifierSelection, validateOrderable } from '@/lib/order-validation';
import { priceOrder, type PricedLine } from '@/lib/pricing';
import { checkOrderRate, clientIpHash, recordOrderPlaced } from '@/lib/rate-limit';
import { getStoreStatus } from '@/lib/store-status';
import { ensureWebOrderColumns } from '@/lib/web-order-columns';
import {
  type PublishedMenu,
  type WebFulfilment,
  type WebOrderItem,
} from '@cheeseoclock/shared-types';

export const dynamic = 'force-dynamic';

/**
 * Public: place a COD order — delivered, or picked up from the shop.
 *
 * Refused unless the POS is currently accepting online orders (see
 * lib/store-status) — an order no till is watching never gets cooked.
 *
 * The client sends posItemId + modifier ids + quantities. We re-price
 * EVERYTHING server-side against the published menu — the client's totals
 * are display-only and never trusted. The POS will re-price again at import
 * (its DB is authoritative), so the worst a stale menu can cause is a small
 * estimate drift on the confirmation page, never a wrong charge: cash is
 * collected against the POS receipt. Totals follow the till's own maths
 * (lib/pricing).
 *
 * Delivery zones (lib/delivery-zones): a delivery must name one of the
 * shop's DHA / Clifton zones, and anything else is refused. The zone's fee
 * rides to the till as the matching "Delivery Charge (Rs N)" menu item, added
 * here — never chosen by the client.
 *
 * Pickup: no zone, no address, the listening till's pickup discount off the
 * order (it announces the percent it will bill) — and only while that till
 * has announced it can import pickup orders, because an older POS would book
 * one as a delivery at full price.
 */

// The messages below reach the customer as written (the checkout shows the
// first field error), so they are sentences, not Zod's defaults.
const OrderItemSchema = z.object({
  posItemId: z.string().min(1),
  quantity: z
    .number()
    .int()
    .min(1)
    .max(50, 'Up to 50 of one item per order — for more, call or WhatsApp us.'),
  modifierIds: z.array(z.string()).max(30).default([]),
  notes: z.string().max(300, 'Keep each item’s note under 300 characters.').optional(),
});

const PlaceOrderSchema = z
  .object({
    /** Absent from pages loaded before pickup existed: a delivery. */
    fulfilment: z.enum(['delivery', 'pickup']).default('delivery'),
    customerName: z
      .string()
      .trim()
      .min(2, 'Please enter your name.')
      .max(80, 'Please shorten your name to 80 characters.'),
    customerPhone: z
      .string()
      .trim()
      .min(7, 'Enter a Pakistani mobile number, like 0300 1234567.')
      .max(20, 'Enter a Pakistani mobile number, like 0300 1234567.'),
    addressLine: z.string().trim().max(300, 'Please shorten the address to 300 characters.').optional(),
    /** One of DELIVERY_ZONES' ids. Required for a delivery: no zone, no delivery. */
    zoneId: z.string().trim().max(40).optional(),
    notes: z.string().trim().max(500, 'Please keep the notes under 500 characters.').optional(),
    items: z
      .array(OrderItemSchema)
      .min(1, 'Your order is empty.')
      .max(50, 'That is a very big order — please call or WhatsApp us to place it.'),
    /**
     * Idempotency key, generated by the browser once per checkout. A double
     * tap, or a retry after a lost response, replays the same id and gets the
     * order that already exists instead of a second one.
     */
    clientOrderId: z.string().uuid().optional(),
    /** Honeypot — real users never fill this hidden field. */
    website: z.string().max(0).optional(),
  })
  .superRefine((v, ctx) => {
    if (v.fulfilment !== 'delivery') return;
    if (!v.zoneId) {
      ctx.addIssue({ code: 'custom', path: ['zoneId'], message: 'Choose your delivery area' });
    }
    if (!v.addressLine || v.addressLine.length < 5) {
      ctx.addIssue({ code: 'custom', path: ['addressLine'], message: 'Enter your house and street' });
    }
  });

/** What a pickup order shows as its address, on the site and at the till. */
const PICKUP_ADDRESS = 'PICK-UP — customer collects from the shop';
const PICKUP_AREA = 'Pick-up';

interface StoredTotals {
  id: string;
  fulfilment: WebFulfilment;
  subtotal_cents: number;
  discount_cents: number;
  tax_cents: number;
  total_cents: number;
}

async function findExisting(id: string): Promise<StoredTotals | null> {
  const rows = (await sql()`
    SELECT id, fulfilment, subtotal_cents, discount_cents, tax_cents, total_cents
      FROM web_orders WHERE id = ${id}
  `) as StoredTotals[];
  return rows[0] ?? null;
}

function placedResponse(row: StoredTotals, replayed: boolean): Response {
  return Response.json({
    ok: true,
    data: {
      orderId: row.id,
      fulfilment: row.fulfilment,
      subtotalCents: row.subtotal_cents,
      discountCents: row.discount_cents,
      taxCents: row.tax_cents,
      totalCents: row.total_cents,
      replayed,
    },
  });
}

export async function POST(req: Request): Promise<Response> {
  try {
    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return Response.json({ ok: false, error: 'bad_request' }, { status: 400 });
    }
    const parsed = PlaceOrderSchema.safeParse(body);
    if (!parsed.success) {
      return Response.json(
        { ok: false, error: 'validation', details: parsed.error.flatten().fieldErrors },
        { status: 400 },
      );
    }
    const input = parsed.data;
    const pickup = input.fulfilment === 'pickup';
    await ensureWebOrderColumns();

    // Same checkout submitted twice (double tap, or a retry after the first
    // response was lost): hand back the order that already exists. Checked
    // before the store gate and the limiter so a replay is never refused or
    // counted.
    if (input.clientOrderId) {
      const existing = await findExisting(input.clientOrderId);
      if (existing) return placedResponse(existing, true);
    }

    // DHA and Clifton only — the owner's rule, not a UI nicety.
    const zone = pickup ? undefined : findZone(input.zoneId);
    if (!pickup && !zone) {
      return Response.json(
        {
          ok: false,
          error: 'outside_zone',
          message:
            'We deliver in DHA and Clifton only. Choose your area from the list — if it is not there, we cannot deliver to it.',
        },
        { status: 400 },
      );
    }

    // The till is the authority on whether anyone is listening. Checked before
    // any pricing work and regardless of what the page showed — a customer who
    // loaded the menu while the shop was open must not slip an order through
    // after it closed.
    const store = await getStoreStatus();
    if (!store.acceptingOrders) {
      return Response.json(
        {
          ok: false,
          error: 'store_closed',
          message:
            'We are not taking online orders at the moment. Please order on WhatsApp or give us a call — we will take it right away.',
        },
        { status: 409 },
      );
    }
    if (pickup && !store.pickupAvailable) {
      return Response.json(
        {
          ok: false,
          error: 'pickup_unavailable',
          message:
            'Online pick-up is not available right now. Choose delivery, or order on WhatsApp and collect from the shop.',
        },
        { status: 409 },
      );
    }

    const phone = normalizePhone(input.customerPhone);
    if (!phone) {
      return Response.json(
        { ok: false, error: 'validation', details: { customerPhone: ['Enter a valid Pakistani mobile number'] } },
        { status: 400 },
      );
    }

    // Flood check before any real work. Fails open — see lib/rate-limit.
    const rate = await checkOrderRate(phone, clientIpHash(req));
    if (!rate.allowed) {
      return Response.json(
        {
          ok: false,
          error: 'rate_limited',
          message:
            'That is a lot of orders in a short window. Please wait a few minutes, or call us and we will take it over the phone.',
        },
        { status: 429, headers: { 'Retry-After': String(rate.retryAfterSec) } },
      );
    }

    // Load the published menu and re-price server-side.
    const menuRows = (await sql()`
      SELECT menu_json FROM site_menu WHERE id = 1
    `) as Array<{ menu_json: PublishedMenu }>;
    const menu = menuRows[0]?.menu_json;
    if (!menu) {
      return Response.json({ ok: false, error: 'menu_not_published' }, { status: 409 });
    }
    const itemIndex = new Map(
      menu.categories.flatMap((c) => c.items.map((i) => [i.posItemId, i] as const)),
    );

    const priced: PricedLine[] = [];
    const lines: WebOrderItem[] = [];
    for (const line of input.items) {
      const item = itemIndex.get(line.posItemId);
      if (!item) {
        return Response.json(
          { ok: false, error: 'item_not_on_menu', itemId: line.posItemId },
          { status: 409 },
        );
      }
      const notOrderable = validateOrderable(item, input.fulfilment);
      if (notOrderable) {
        return Response.json(
          { ok: false, error: 'not_deliverable', message: notOrderable },
          { status: 409 },
        );
      }
      const groupError = validateModifierSelection(item, line.modifierIds);
      if (groupError) {
        return Response.json(
          { ok: false, error: 'invalid_modifiers', message: groupError },
          { status: 409 },
        );
      }
      const allMods = item.modifierGroups.flatMap((g) => g.modifiers);
      const modIndex = new Map(allMods.map((m) => [m.posModifierId, m] as const));
      const mods = [];
      let unit = item.basePriceCents;
      for (const modId of line.modifierIds) {
        const mod = modIndex.get(modId);
        if (!mod) {
          return Response.json(
            { ok: false, error: 'modifier_not_on_item', modifierId: modId },
            { status: 409 },
          );
        }
        unit += mod.priceDeltaCents;
        mods.push({
          posModifierId: mod.posModifierId,
          name: mod.name,
          priceDeltaCents: mod.priceDeltaCents,
        });
      }
      priced.push({ lineTotalCents: unit * line.quantity, taxRateBps: item.taxRateBps });
      lines.push({
        posItemId: item.posItemId,
        name: item.name,
        quantity: line.quantity,
        unitPriceCents: unit,
        modifiers: mods,
        notes: line.notes?.trim() || null,
      });
    }

    let orderNotes = input.notes?.trim() || null;
    if (zone) {
      // The zone's fee, as the till's own delivery-charge item so the receipt
      // and the rider's cash agree. A till that has not imported those items
      // yet still gets the order, with the fee spelled out for the cashier.
      const feeItem = deliveryChargeItemFor(menu, zone.feeCents);
      if (feeItem) {
        priced.push({ lineTotalCents: feeItem.basePriceCents, taxRateBps: feeItem.taxRateBps });
        lines.push({
          posItemId: feeItem.posItemId,
          name: feeItem.name,
          quantity: 1,
          unitPriceCents: feeItem.basePriceCents,
          modifiers: [],
          notes: null,
        });
      } else {
        priced.push({ lineTotalCents: zone.feeCents, taxRateBps: 0 });
        const reminder = `Delivery ${zone.name} ${formatCents(zone.feeCents)} — add the delivery charge by hand`;
        orderNotes = orderNotes ? `${reminder}. ${orderNotes}` : reminder;
      }
    }
    // The till caps order notes at 500 and prefixes "[web] " — stay under it
    // or the import fails validation and retries until it gives up.
    if (orderNotes && orderNotes.length > 490) orderNotes = orderNotes.slice(0, 490);

    const totals = priceOrder(priced, pickup ? store.pickupDiscountPercent : 0);

    const id = input.clientOrderId ?? uuidv7();
    const inserted = (await sql()`
      INSERT INTO web_orders
        (id, status, customer_name, customer_phone, address_line, area, notes,
         items_json, subtotal_cents, discount_cents, tax_cents, total_cents,
         payment_method, fulfilment)
      VALUES
        (${id}, 'new', ${input.customerName.trim()}, ${phone},
         ${pickup ? PICKUP_ADDRESS : input.addressLine!.trim()},
         ${pickup ? PICKUP_AREA : zone!.name},
         ${orderNotes}, ${JSON.stringify(lines)},
         ${totals.subtotalCents}, ${totals.discountCents}, ${totals.taxCents},
         ${totals.totalCents}, 'cod', ${input.fulfilment})
      ON CONFLICT (id) DO NOTHING
      RETURNING id
    `) as Array<{ id: string }>;
    if (inserted.length === 0) {
      // Two requests raced past the check above; the other one won.
      const existing = await findExisting(id);
      if (existing) return placedResponse(existing, true);
    }

    await recordOrderPlaced(clientIpHash(req));

    return Response.json({
      ok: true,
      data: { orderId: id, fulfilment: input.fulfilment, ...totals, replayed: false },
    });
  } catch (e) {
    console.error('POST /api/orders failed', e);
    return Response.json({ ok: false, error: 'internal' }, { status: 500 });
  }
}
