import { v7 as uuidv7 } from 'uuid';
import { z } from 'zod';
import { sql } from '@/lib/db';
import { deliveryChargeItemFor, findZone } from '@/lib/delivery-zones';
import { formatCents, normalizePhone } from '@/lib/format';
import { validateModifierSelection, validateOrderable } from '@/lib/order-validation';
import { checkOrderRate, clientIpHash, recordOrderPlaced } from '@/lib/rate-limit';
import { getStoreStatus } from '@/lib/store-status';
import type { PublishedMenu, WebOrderItem } from '@cheeseoclock/shared-types';

export const dynamic = 'force-dynamic';

/**
 * Public: place a COD order.
 *
 * Refused unless the POS is currently accepting online orders (see
 * lib/store-status) — an order no till is watching never gets cooked.
 *
 * The client sends posItemId + modifier ids + quantities. We re-price
 * EVERYTHING server-side against the published menu — the client's totals
 * are display-only and never trusted. The POS will re-price again at import
 * (its DB is authoritative), so the worst a stale menu can cause is a small
 * estimate drift on the confirmation page, never a wrong charge: COD is
 * collected against the POS receipt.
 *
 * Delivery zones (lib/delivery-zones): the customer must pick one of the
 * shop's DHA / Clifton zones, and anything else is refused. The zone's fee
 * rides to the till as the matching "Delivery Charge (Rs N)" menu item, added
 * here — never chosen by the client.
 */

const OrderItemSchema = z.object({
  posItemId: z.string().min(1),
  quantity: z.number().int().min(1).max(50),
  modifierIds: z.array(z.string()).max(30).default([]),
  notes: z.string().max(300).optional(),
});

const PlaceOrderSchema = z.object({
  customerName: z.string().trim().min(2).max(80),
  customerPhone: z.string().trim().min(7).max(20),
  addressLine: z.string().trim().min(5).max(300),
  /** One of DELIVERY_ZONES' ids. Required: no zone, no delivery. */
  zoneId: z.string({ required_error: 'Choose your delivery area' }).trim().min(1, 'Choose your delivery area').max(40),
  notes: z.string().trim().max(500).optional(),
  items: z.array(OrderItemSchema).min(1).max(50),
  /**
   * Idempotency key, generated by the browser once per checkout. A double
   * tap, or a retry after a lost response, replays the same id and gets the
   * order that already exists instead of a second one.
   */
  clientOrderId: z.string().uuid().optional(),
  /** Honeypot — real users never fill this hidden field. */
  website: z.string().max(0).optional(),
});

interface StoredTotals {
  id: string;
  subtotal_cents: number;
  tax_cents: number;
  total_cents: number;
}

async function findExisting(id: string): Promise<StoredTotals | null> {
  const rows = (await sql()`
    SELECT id, subtotal_cents, tax_cents, total_cents FROM web_orders WHERE id = ${id}
  `) as StoredTotals[];
  return rows[0] ?? null;
}

function placedResponse(row: StoredTotals, replayed: boolean): Response {
  return Response.json({
    ok: true,
    data: {
      orderId: row.id,
      subtotalCents: row.subtotal_cents,
      taxCents: row.tax_cents,
      totalCents: row.total_cents,
      replayed,
    },
  });
}

export async function POST(req: Request): Promise<Response> {
  try {
    const body: unknown = await req.json();
    const parsed = PlaceOrderSchema.safeParse(body);
    if (!parsed.success) {
      return Response.json(
        { ok: false, error: 'validation', details: parsed.error.flatten().fieldErrors },
        { status: 400 },
      );
    }
    const input = parsed.data;

    // Same checkout submitted twice (double tap, or a retry after the first
    // response was lost): hand back the order that already exists. Checked
    // before the store gate and the limiter so a replay is never refused or
    // counted.
    if (input.clientOrderId) {
      const existing = await findExisting(input.clientOrderId);
      if (existing) return placedResponse(existing, true);
    }

    // DHA and Clifton only — the owner's rule, not a UI nicety.
    const zone = findZone(input.zoneId);
    if (!zone) {
      return Response.json(
        {
          ok: false,
          error: 'outside_zone',
          message:
            'We deliver in DHA and Clifton only. Choose your area from the list — if it is not there, we cannot deliver to it.',
        },
        { status: 400 },
      );
    }

    // The till is the authority on whether anyone is listening. Checked before
    // any pricing work and regardless of what the page showed — a customer who
    // loaded the menu while the shop was open must not slip an order through
    // after it closed.
    const store = await getStoreStatus();
    if (!store.acceptingOrders) {
      return Response.json(
        {
          ok: false,
          error: 'store_closed',
          message:
            'We are not taking online orders at the moment. Please order on WhatsApp or give us a call — we will take it right away.',
        },
        { status: 409 },
      );
    }

    const phone = normalizePhone(input.customerPhone);
    if (!phone) {
      return Response.json(
        { ok: false, error: 'validation', details: { customerPhone: ['Enter a valid Pakistani mobile number'] } },
        { status: 400 },
      );
    }

    // Flood check before any real work. Fails open — see lib/rate-limit.
    const rate = await checkOrderRate(phone, clientIpHash(req));
    if (!rate.allowed) {
      return Response.json(
        {
          ok: false,
          error: 'rate_limited',
          message:
            'That is a lot of orders in a short window. Please wait a few minutes, or call us and we will take it over the phone.',
        },
        { status: 429, headers: { 'Retry-After': String(rate.retryAfterSec) } },
      );
    }

    // Load the published menu and re-price server-side.
    const menuRows = (await sql()`
      SELECT menu_json FROM site_menu WHERE id = 1
    `) as Array<{ menu_json: PublishedMenu }>;
    const menu = menuRows[0]?.menu_json;
    if (!menu) {
      return Response.json({ ok: false, error: 'menu_not_published' }, { status: 409 });
    }
    const itemIndex = new Map(
      menu.categories.flatMap((c) => c.items.map((i) => [i.posItemId, i] as const)),
    );

    let subtotalCents = 0;
    let taxCents = 0;
    const lines: WebOrderItem[] = [];
    for (const line of input.items) {
      const item = itemIndex.get(line.posItemId);
      if (!item) {
        return Response.json(
          { ok: false, error: 'item_not_on_menu', itemId: line.posItemId },
          { status: 409 },
        );
      }
      const notOrderable = validateOrderable(item);
      if (notOrderable) {
        return Response.json(
          { ok: false, error: 'not_deliverable', message: notOrderable },
          { status: 409 },
        );
      }
      const groupError = validateModifierSelection(item, line.modifierIds);
      if (groupError) {
        return Response.json(
          { ok: false, error: 'invalid_modifiers', message: groupError },
          { status: 409 },
        );
      }
      const allMods = item.modifierGroups.flatMap((g) => g.modifiers);
      const modIndex = new Map(allMods.map((m) => [m.posModifierId, m] as const));
      const mods = [];
      let unit = item.basePriceCents;
      for (const modId of line.modifierIds) {
        const mod = modIndex.get(modId);
        if (!mod) {
          return Response.json(
            { ok: false, error: 'modifier_not_on_item', modifierId: modId },
            { status: 409 },
          );
        }
        unit += mod.priceDeltaCents;
        mods.push({
          posModifierId: mod.posModifierId,
          name: mod.name,
          priceDeltaCents: mod.priceDeltaCents,
        });
      }
      const lineTotal = unit * line.quantity;
      subtotalCents += lineTotal;
      // Exclusive tax estimate (mirrors the POS): line total × rate.
      taxCents += Math.round((lineTotal * item.taxRateBps) / 10_000);
      lines.push({
        posItemId: item.posItemId,
        name: item.name,
        quantity: line.quantity,
        unitPriceCents: unit,
        modifiers: mods,
        notes: line.notes?.trim() || null,
      });
    }

    // The zone's fee, as the till's own delivery-charge item so the receipt
    // and the rider's cash agree. A till that has not imported those items
    // yet still gets the order, with the fee spelled out for the cashier.
    let orderNotes = input.notes?.trim() || null;
    const feeItem = deliveryChargeItemFor(menu, zone.feeCents);
    if (feeItem) {
      subtotalCents += feeItem.basePriceCents;
      taxCents += Math.round((feeItem.basePriceCents * feeItem.taxRateBps) / 10_000);
      lines.push({
        posItemId: feeItem.posItemId,
        name: feeItem.name,
        quantity: 1,
        unitPriceCents: feeItem.basePriceCents,
        modifiers: [],
        notes: null,
      });
    } else {
      subtotalCents += zone.feeCents;
      const reminder = `Delivery ${zone.name} ${formatCents(zone.feeCents)} — add the delivery charge by hand`;
      orderNotes = orderNotes ? `${reminder}. ${orderNotes}` : reminder;
    }
    // The till caps order notes at 500 and prefixes "[web] " — stay under it
    // or the import fails validation and retries until it gives up.
    if (orderNotes && orderNotes.length > 490) orderNotes = orderNotes.slice(0, 490);
    const totalCents = subtotalCents + taxCents;

    const id = input.clientOrderId ?? uuidv7();
    const inserted = (await sql()`
      INSERT INTO web_orders
        (id, status, customer_name, customer_phone, address_line, area, notes,
         items_json, subtotal_cents, tax_cents, total_cents, payment_method)
      VALUES
        (${id}, 'new', ${input.customerName.trim()}, ${phone},
         ${input.addressLine.trim()}, ${zone.name},
         ${orderNotes}, ${JSON.stringify(lines)},
         ${subtotalCents}, ${taxCents}, ${totalCents}, 'cod')
      ON CONFLICT (id) DO NOTHING
      RETURNING id
    `) as Array<{ id: string }>;
    if (inserted.length === 0) {
      // Two requests raced past the check above; the other one won.
      const existing = await findExisting(id);
      if (existing) return placedResponse(existing, true);
    }

    await recordOrderPlaced(clientIpHash(req));

    return Response.json({
      ok: true,
      data: { orderId: id, subtotalCents, taxCents, totalCents, replayed: false },
    });
  } catch (e) {
    console.error('POST /api/orders failed', e);
    return Response.json({ ok: false, error: 'internal' }, { status: 500 });
  }
}
