import { v7 as uuidv7 } from 'uuid';
import { z } from 'zod';
import { sql } from '@/lib/db';
import {
  deliveryMinimumMessage,
  factsFromBlock,
  findFactZone,
  outsideZoneMessage,
  zonePausedMessage,
} from '@/lib/delivery-facts';
import { feeItemIdsOf, zoneFeeItemFor } from '@/lib/delivery-zones';
import { formatCents, normalizePhone } from '@/lib/format';
import { menuWithoutDrinkBrand } from '@/lib/menu-view';
import { validateModifierSelection, validateOrderable } from '@/lib/order-validation';
import { priceOrder, type PricedLine } from '@/lib/pricing';
import { checkOrderRate, clientIpHash, recordOrderPlaced } from '@/lib/rate-limit';
import { parseStoredSettings } from '@/lib/site-facts';
import { getStoreStatus } from '@/lib/store-status';
import { ensureWebOrderColumns } from '@/lib/web-order-columns';
import {
  closedNoticeInForce,
  deliveryMinimumShortfallCents,
  type PublishedMenu,
  type WebFulfilment,
  type WebOrderItem,
} from '@cheeseoclock/shared-types';

export const dynamic = 'force-dynamic';

/**
 * Public: place a COD order — delivered, or picked up from the shop.
 *
 * Refused unless the POS is currently accepting online orders (see
 * lib/store-status) — an order no till is watching never gets cooked.
 *
 * The client sends posItemId + modifier ids + quantities. We re-price
 * EVERYTHING server-side against the published menu — the client's totals
 * are display-only and never trusted. The POS will re-price again at import
 * (its DB is authoritative), so the worst a stale menu can cause is a small
 * estimate drift on the confirmation page, never a wrong charge: cash is
 * collected against the POS receipt. Totals follow the till's own maths
 * (lib/pricing).
 *
 * Delivery areas (lib/delivery-facts): a delivery must name one of the
 * areas the owner delivers to — the settings block stored with the menu
 * (Settings → Delivery areas & fees on the till), or the compiled DHA /
 * Clifton list until a block arrives. Anything else is refused, and so is an
 * area the owner has switched off. The area's fee rides to the till as its
 * "Delivery Charge (Rs N)" menu item, added here — never chosen by the
 * client: the area's own fee item (feeItemId) when the menu has it at the
 * fee, else today's match by name and price, else a note for the cashier to
 * add it by hand.
 *
 * Pickup: no zone, no address, the owner's pick-up % off the order (the
 * settings block's, or before one the listening till's announced %) — and
 * only while the owner offers it and that till has announced it can import
 * pickup orders, because an older POS would book one as a delivery at full
 * price.
 *
 * The owner's website messages (v0.7.30, shared-types web-bridge.ts WEBSITE
 * MESSAGES), from the same block: while the shop is closed, the owner's
 * closed notice (until its last Karachi day) is the store_closed sentence;
 * and a DELIVERY whose food is under the owner's smallest delivery order is
 * refused ('below_minimum') after pricing — a pick-up never is. With neither
 * stored, exactly as before.
 */

/** Today's store_closed sentence: what a closed shop says with no closed notice of the owner's. */
const STORE_CLOSED_MESSAGE =
  'We are not taking online orders at the moment. Please order on WhatsApp or give us a call — we will take it right away.';

// The messages below reach the customer as written (the checkout shows the
// first field error), so they are sentences, not Zod's defaults.
const OrderItemSchema = z.object({
  posItemId: z.string().min(1),
  quantity: z
    .number()
    .int()
    .min(1)
    .max(50, 'Up to 50 of one item per order — for more, call or WhatsApp us.'),
  modifierIds: z.array(z.string()).max(30).default([]),
  notes: z.string().max(300, 'Keep each item’s note under 300 characters.').optional(),
});

const PlaceOrderSchema = z
  .object({
    /** Absent from pages loaded before pickup existed: a delivery. */
    fulfilment: z.enum(['delivery', 'pickup']).default('delivery'),
    customerName: z
      .string()
      .trim()
      .min(2, 'Please enter your name.')
      .max(80, 'Please shorten your name to 80 characters.'),
    customerPhone: z
      .string()
      .trim()
      .min(7, 'Enter a Pakistani mobile number, like 0300 1234567.')
      .max(20, 'Enter a Pakistani mobile number, like 0300 1234567.'),
    addressLine: z.string().trim().max(300, 'Please shorten the address to 300 characters.').optional(),
    /** An area id (the settings block's, else the compiled list's). Required for a delivery: no zone, no delivery. */
    zoneId: z.string().trim().max(40).optional(),
    notes: z.string().trim().max(500, 'Please keep the notes under 500 characters.').optional(),
    items: z
      .array(OrderItemSchema)
      .min(1, 'Your order is empty.')
      .max(50, 'That is a very big order — please call or WhatsApp us to place it.'),
    /**
     * Idempotency key, generated by the browser once per checkout. A double
     * tap, or a retry after a lost response, replays the same id and gets the
     * order that already exists instead of a second one.
     */
    clientOrderId: z.string().uuid().optional(),
    /** Honeypot — real users never fill this hidden field. */
    website: z.string().max(0).optional(),
  })
  .superRefine((v, ctx) => {
    if (v.fulfilment !== 'delivery') return;
    if (!v.zoneId) {
      ctx.addIssue({ code: 'custom', path: ['zoneId'], message: 'Choose your delivery area' });
    }
    if (!v.addressLine || v.addressLine.length < 5) {
      ctx.addIssue({ code: 'custom', path: ['addressLine'], message: 'Enter your house and street' });
    }
  });

/** What a pickup order shows as its address, on the site and at the till. */
const PICKUP_ADDRESS = 'PICK-UP — customer collects from the shop';
const PICKUP_AREA = 'Pick-up';

interface StoredTotals {
  id: string;
  fulfilment: WebFulfilment;
  subtotal_cents: number;
  discount_cents: number;
  tax_cents: number;
  total_cents: number;
}

async function findExisting(id: string): Promise<StoredTotals | null> {
  const rows = (await sql()`
    SELECT id, fulfilment, subtotal_cents, discount_cents, tax_cents, total_cents
      FROM web_orders WHERE id = ${id}
  `) as StoredTotals[];
  return rows[0] ?? null;
}

function placedResponse(row: StoredTotals, replayed: boolean): Response {
  return Response.json({
    ok: true,
    data: {
      orderId: row.id,
      fulfilment: row.fulfilment,
      subtotalCents: row.subtotal_cents,
      discountCents: row.discount_cents,
      taxCents: row.tax_cents,
      totalCents: row.total_cents,
      replayed,
    },
  });
}

export async function POST(req: Request): Promise<Response> {
  try {
    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return Response.json({ ok: false, error: 'bad_request' }, { status: 400 });
    }
    const parsed = PlaceOrderSchema.safeParse(body);
    if (!parsed.success) {
      return Response.json(
        { ok: false, error: 'validation', details: parsed.error.flatten().fieldErrors },
        { status: 400 },
      );
    }
    const input = parsed.data;
    const pickup = input.fulfilment === 'pickup';
    await ensureWebOrderColumns();

    // Same checkout submitted twice (double tap, or a retry after the first
    // response was lost): hand back the order that already exists. Checked
    // before the store gate and the limiter so a replay is never refused or
    // counted.
    if (input.clientOrderId) {
      const existing = await findExisting(input.clientOrderId);
      if (existing) return placedResponse(existing, true);
    }

    // Where the owner delivers: the settings block stored with the menu, else
    // the built-in areas. Only the block here (the menu, with its images, is
    // read after the flood check below).
    const settingsRows = (await sql()`
      SELECT menu_json -> 'settings' AS settings FROM site_menu WHERE id = 1
    `) as Array<{ settings: unknown }>;
    const block = parseStoredSettings(settingsRows[0]?.settings ?? null);
    const facts = factsFromBlock(block);

    // Only where the owner delivers — the owner's rule, not a UI nicety.
    const zoneAsked = pickup ? undefined : findFactZone(facts, input.zoneId);
    if (!pickup && !zoneAsked) {
      return Response.json(
        { ok: false, error: 'outside_zone', message: outsideZoneMessage(facts) },
        { status: 400 },
      );
    }
    if (zoneAsked && !zoneAsked.active) {
      return Response.json(
        { ok: false, error: 'zone_paused', message: zonePausedMessage(zoneAsked) },
        { status: 400 },
      );
    }

    // The till is the authority on whether anyone is listening. Checked before
    // any pricing work and regardless of what the page showed — a customer who
    // loaded the menu while the shop was open must not slip an order through
    // after it closed.
    const store = await getStoreStatus();
    if (!store.acceptingOrders) {
      // The owner's closed notice while it is in force (its last Karachi day included), else today's words.
      return Response.json(
        {
          ok: false,
          error: 'store_closed',
          message: closedNoticeInForce(block?.closedNotice, Date.now()) ?? STORE_CLOSED_MESSAGE,
        },
        { status: 409 },
      );
    }
    if (pickup && !store.pickupAvailable) {
      return Response.json(
        {
          ok: false,
          error: 'pickup_unavailable',
          message:
            'Online pick-up is not available right now. Choose delivery, or order on WhatsApp and collect from the shop.',
        },
        { status: 409 },
      );
    }

    const phone = normalizePhone(input.customerPhone);
    if (!phone) {
      return Response.json(
        { ok: false, error: 'validation', details: { customerPhone: ['Enter a valid Pakistani mobile number'] } },
        { status: 400 },
      );
    }

    // Flood check before any real work. Fails open — see lib/rate-limit.
    const rate = await checkOrderRate(phone, clientIpHash(req));
    if (!rate.allowed) {
      return Response.json(
        {
          ok: false,
          error: 'rate_limited',
          message:
            'That is a lot of orders in a short window. Please wait a few minutes, or call us and we will take it over the phone.',
        },
        { status: 429, headers: { 'Retry-After': String(rate.retryAfterSec) } },
      );
    }

    // Load the published menu and re-price server-side. Brand-free names (the
    // till sells drinks as "Pepsi"; customers read "Cola"): what the order
    // stores and every message below says them as the menu page did. Ids and
    // prices are the till's own — it imports by id.
    const menuRows = (await sql()`
      SELECT menu_json FROM site_menu WHERE id = 1
    `) as Array<{ menu_json: PublishedMenu }>;
    const menu = menuRows[0] ? menuWithoutDrinkBrand(menuRows[0].menu_json) : undefined;
    if (!menu) {
      return Response.json({ ok: false, error: 'menu_not_published' }, { status: 409 });
    }
    // The area again, from the block stored WITH this menu (the same row, the same read): a till's
    // publish that landed since the check above may have moved the fee to a new item this menu
    // carries and the old one does not — the fee and its item must come from one publish.
    const priceFacts = factsFromBlock(parseStoredSettings(menuRows[0]?.menu_json.settings ?? null));
    const zoneNow = pickup ? undefined : findFactZone(priceFacts, input.zoneId);
    if (!pickup && !zoneNow) {
      return Response.json(
        { ok: false, error: 'outside_zone', message: outsideZoneMessage(priceFacts) },
        { status: 400 },
      );
    }
    if (zoneNow && !zoneNow.active) {
      return Response.json(
        { ok: false, error: 'zone_paused', message: zonePausedMessage(zoneNow) },
        { status: 400 },
      );
    }
    const itemIndex = new Map(
      menu.categories.flatMap((c) => c.items.map((i) => [i.posItemId, i] as const)),
    );
    const feeItemIds = feeItemIdsOf(menu);

    const priced: PricedLine[] = [];
    const lines: WebOrderItem[] = [];
    for (const line of input.items) {
      const item = itemIndex.get(line.posItemId);
      if (!item) {
        return Response.json(
          { ok: false, error: 'item_not_on_menu', itemId: line.posItemId },
          { status: 409 },
        );
      }
      const notOrderable = validateOrderable(item, input.fulfilment, feeItemIds);
      if (notOrderable) {
        return Response.json(
          { ok: false, error: 'not_deliverable', message: notOrderable },
          { status: 409 },
        );
      }
      const groupError = validateModifierSelection(item, line.modifierIds);
      if (groupError) {
        return Response.json(
          { ok: false, error: 'invalid_modifiers', message: groupError },
          { status: 409 },
        );
      }
      const allMods = item.modifierGroups.flatMap((g) => g.modifiers);
      const modIndex = new Map(allMods.map((m) => [m.posModifierId, m] as const));
      const mods = [];
      let unit = item.basePriceCents;
      for (const modId of line.modifierIds) {
        const mod = modIndex.get(modId);
        if (!mod) {
          return Response.json(
            { ok: false, error: 'modifier_not_on_item', modifierId: modId },
            { status: 409 },
          );
        }
        unit += mod.priceDeltaCents;
        mods.push({
          posModifierId: mod.posModifierId,
          name: mod.name,
          priceDeltaCents: mod.priceDeltaCents,
        });
      }
      priced.push({ lineTotalCents: unit * line.quantity, taxRateBps: item.taxRateBps });
      lines.push({
        posItemId: item.posItemId,
        name: item.name,
        quantity: line.quantity,
        unitPriceCents: unit,
        modifiers: mods,
        notes: line.notes?.trim() || null,
      });
    }

    // The owner's smallest website DELIVERY order (the block stored with this menu; 0 = none, as
    // before): the food just priced — each line with its choices, times its quantity — before tax,
    // the delivery charge (added below) and any discount. A pick-up is never refused.
    if (!pickup) {
      const minimum = priceFacts.minDeliveryOrderCents;
      const food = priced.reduce((sum, l) => sum + l.lineTotalCents, 0);
      const short = deliveryMinimumShortfallCents(food, minimum);
      if (short > 0) {
        return Response.json(
          { ok: false, error: 'below_minimum', message: deliveryMinimumMessage(minimum, short, store.pickupAvailable) },
          { status: 409 },
        );
      }
    }

    let orderNotes = input.notes?.trim() || null;
    const zone = zoneNow;
    if (zone && zone.feeCents > 0) {
      // The area's fee, as the till's own delivery-charge item so the receipt
      // and the rider's cash agree: its own item (feeItemId), else the item
      // named for that fee. A till whose menu has neither (it has not
      // imported them, or an older till published over a kept block) still
      // gets the order, with the fee spelled out for the cashier. A free area
      // has no charge line.
      const feeItem = zoneFeeItemFor(menu, zone);
      if (feeItem) {
        priced.push({ lineTotalCents: feeItem.basePriceCents, taxRateBps: feeItem.taxRateBps });
        lines.push({
          posItemId: feeItem.posItemId,
          name: feeItem.name,
          quantity: 1,
          unitPriceCents: feeItem.basePriceCents,
          modifiers: [],
          notes: null,
        });
      } else {
        priced.push({ lineTotalCents: zone.feeCents, taxRateBps: 0 });
        const reminder = `Delivery ${zone.name} ${formatCents(zone.feeCents)} — add the delivery charge by hand`;
        orderNotes = orderNotes ? `${reminder}. ${orderNotes}` : reminder;
      }
    }
    // The till caps order notes at 500 and prefixes "[web] " — stay under it
    // or the import fails validation and retries until it gives up.
    if (orderNotes && orderNotes.length > 490) orderNotes = orderNotes.slice(0, 490);

    const totals = priceOrder(priced, pickup ? store.pickupDiscountPercent : 0);

    const id = input.clientOrderId ?? uuidv7();
    const inserted = (await sql()`
      INSERT INTO web_orders
        (id, status, customer_name, customer_phone, address_line, area, notes,
         items_json, subtotal_cents, discount_cents, tax_cents, total_cents,
         payment_method, fulfilment)
      VALUES
        (${id}, 'new', ${input.customerName.trim()}, ${phone},
         ${pickup ? PICKUP_ADDRESS : input.addressLine!.trim()},
         ${pickup ? PICKUP_AREA : zone!.name},
         ${orderNotes}, ${JSON.stringify(lines)},
         ${totals.subtotalCents}, ${totals.discountCents}, ${totals.taxCents},
         ${totals.totalCents}, 'cod', ${input.fulfilment})
      ON CONFLICT (id) DO NOTHING
      RETURNING id
    `) as Array<{ id: string }>;
    if (inserted.length === 0) {
      // Two requests raced past the check above; the other one won.
      const existing = await findExisting(id);
      if (existing) return placedResponse(existing, true);
    }

    await recordOrderPlaced(clientIpHash(req));

    return Response.json({
      ok: true,
      data: { orderId: id, fulfilment: input.fulfilment, ...totals, replayed: false },
    });
  } catch (e) {
    console.error('POST /api/orders failed', e);
    return Response.json({ ok: false, error: 'internal' }, { status: 500 });
  }
}
